/**
 * GENERATED — do not edit by hand.
 *
 *   npx tsx scripts/derive-plf-2025-chart-map.ts <actual-budget-v1.xlsx>
 *
 * The rule that produced every line lives in `plf-legacy-chart.ts`
 * (`deriveLegacyChartMap`): match the normalised LABEL among codes the leaf
 * rule accepts on both sides, and where two candidates exist keep the 2025
 * code's own section. `plf-2025-chart-rederive.test.ts` re-runs the script
 * against the workbook and fails if this file is not what comes out.
 *
 * Source: `PLF Actual 2025` (legacy) against `PLF Budget 2026` +
 * `PLF Actual 2026` (current), from `actual-budget-v1.xlsx`.
 */

import { legacyEntryKey, type LegacyChartEntry } from "./plf-legacy-chart"

/** The calendar year whose chart of accounts these entries describe. */
export const PLF_LEGACY_CHART_YEAR = 2025

export const PLF_2025_CHART_ENTRIES: readonly LegacyChartEntry[] = [
  { code: "PLF.01.01.99", label: "Revenue from Sale of Other Products", kind: "identical", storedCode: "PLF.01.01.99" },
  { code: "PLF.02.01.99", label: "Other Costs", kind: "renumbered", storedCode: "PLF.02.01.99", via: "override", overrideReason: "Farming's other-products cost. The 2026 chart renamed it to \"Other Products' Costs\", so the label rule sent it to the only remaining \"Other Costs\" — PLF.02.03.99, which is the OTHER-SOURCES cost account. Its revenue PLF.01.01.99 stayed put, which is why 1,921,539 of other products showed no cost at all. The 2025 elimination block pairs it with PLF.01.01.99 by adjacency, exactly as it pairs corn with corn costs." },
  { code: "PLF.04.02.01", label: "Subscription Fee", kind: "renumbered", storedCode: "PLF.04.01.01", via: "unique" },
  { code: "PLF.04.02.02", label: "Participation in Forums & Exhibitions", kind: "renumbered", storedCode: "PLF.04.01.02", via: "unique" },
  { code: "PLF.04.02.04", label: "Charity & Donations", kind: "renumbered", storedCode: "PLF.04.01.04", via: "section-kept" },
  { code: "PLF.04.02.05", label: "Meeting with Potential Clients", kind: "renumbered", storedCode: "PLF.04.01.05", via: "unique" },
  { code: "PLF.04.02.06", label: "Marketing Research Expenses", kind: "renumbered", storedCode: "PLF.04.01.06", via: "unique" },
  { code: "PLF.04.02.99", label: "Other Promotional & Research Expenses", kind: "renumbered", storedCode: "PLF.04.01.99", via: "unique" },
  { code: "PLF.04.03.01", label: "Sales Commission Fees", kind: "renumbered", storedCode: "PLF.04.02.01", via: "unique" },
  { code: "PLF.04.04.03", label: "Staff Salaries, State Social Fund Fees", kind: "renumbered", storedCode: "PLF.04.03.03", via: "section-kept" },
  { code: "PLF.04.04.14", label: "Other Payroll Costs", kind: "renumbered", storedCode: "PLF.04.03.99", via: "section-kept" },
  { code: "PLF.04.04.25", label: "Voluntary Medical Insurance", kind: "renumbered", storedCode: "PLF.04.03.05", via: "section-kept" },
  { code: "PLF.04.04.26", label: "Obligatory Accident Insurance", kind: "renumbered", storedCode: "PLF.04.03.06", via: "section-kept" },
  { code: "PLF.04.04.27", label: "Entertainment Expenses", kind: "renumbered", storedCode: "PLF.04.03.07", via: "section-kept" },
  { code: "PLF.04.04.28", label: "Catering Expenses", kind: "renumbered", storedCode: "PLF.04.03.08", via: "section-kept" },
  { code: "PLF.04.05.99", label: "Business Trips Other Costs", kind: "renumbered", storedCode: "PLF.04.04.99", via: "section-kept" },
  { code: "PLF.04.06.01", label: "Audit Fees", kind: "renumbered", storedCode: "PLF.04.05.01", via: "section-kept" },
  { code: "PLF.04.06.02", label: "Consulting Fees & Due Diligence", kind: "renumbered", storedCode: "PLF.04.05.02", via: "unique" },
  { code: "PLF.04.06.03", label: "Legal & Notary Service Fees", kind: "renumbered", storedCode: "PLF.04.05.03", via: "section-kept" },
  { code: "PLF.04.06.04", label: "Brokerage Fees", kind: "renumbered", storedCode: "PLF.04.05.04", via: "section-kept" },
  { code: "PLF.04.06.99", label: "Other Professional Services", kind: "renumbered", storedCode: "PLF.04.05.99", via: "section-kept" },
  { code: "PLF.04.07.01", label: "Electricity Expenses", kind: "renumbered", storedCode: "PLF.04.06.01", via: "section-kept" },
  { code: "PLF.04.07.02", label: "Gas Expenses", kind: "renumbered", storedCode: "PLF.04.06.02", via: "section-kept" },
  { code: "PLF.04.07.03", label: "Heating Expenses", kind: "renumbered", storedCode: "PLF.04.06.03", via: "section-kept" },
  { code: "PLF.04.07.04", label: "Sewers Expenses", kind: "renumbered", storedCode: "PLF.04.06.04", via: "section-kept" },
  { code: "PLF.04.07.05", label: "Waste Disposal Expenses", kind: "renumbered", storedCode: "PLF.04.06.05", via: "section-kept" },
  { code: "PLF.04.07.06", label: "Water Expenses", kind: "renumbered", storedCode: "PLF.04.06.06", via: "section-kept" },
  { code: "PLF.04.07.07", label: "Landline Expenses", kind: "renumbered", storedCode: "PLF.04.06.07", via: "section-kept" },
  { code: "PLF.04.07.08", label: "Mobile Expenses", kind: "renumbered", storedCode: "PLF.04.06.08", via: "section-kept" },
  { code: "PLF.04.07.09", label: "Internet Expenses", kind: "renumbered", storedCode: "PLF.04.06.09", via: "section-kept" },
  { code: "PLF.04.07.10", label: "Postal and Courier Services", kind: "renumbered", storedCode: "PLF.04.06.10", via: "section-kept" },
  { code: "PLF.04.07.99", label: "Other Utilities & Communication Services", kind: "renumbered", storedCode: "PLF.04.06.99", via: "section-kept" },
  { code: "PLF.04.08.01", label: "Rent of Office & Administrative Buildings", kind: "renumbered", storedCode: "PLF.04.07.01", via: "section-kept" },
  { code: "PLF.04.08.03", label: "Rent of Warehouse", kind: "renumbered", storedCode: "PLF.04.07.02", via: "section-kept" },
  { code: "PLF.04.08.99", label: "Rent of Other Assets", kind: "renumbered", storedCode: "PLF.04.07.99", via: "section-kept" },
  { code: "PLF.04.09.01", label: "Office Supplies & Materials", kind: "renumbered", storedCode: "PLF.04.08.01", via: "section-kept" },
  { code: "PLF.04.09.02", label: "IT Expenses", kind: "renumbered", storedCode: "PLF.04.08.02", via: "section-kept" },
  { code: "PLF.04.09.99", label: "Other Office Expenses", kind: "renumbered", storedCode: "PLF.04.08.99", via: "section-kept" },
  { code: "PLF.04.10.01", label: "Fuel", kind: "renumbered", storedCode: "PLF.04.09.01", via: "section-kept" },
  { code: "PLF.04.10.02", label: "Vehicle Insurance", kind: "renumbered", storedCode: "PLF.04.09.02", via: "section-kept" },
  { code: "PLF.04.10.03", label: "Vehicle Repair & Maintenance", kind: "renumbered", storedCode: "PLF.04.09.03", via: "section-kept" },
  { code: "PLF.04.10.04", label: "Parking & Washing", kind: "renumbered", storedCode: "PLF.04.09.04", via: "section-kept" },
  { code: "PLF.04.10.99", label: "Other Transportation Expenses", kind: "renumbered", storedCode: "PLF.04.09.99", via: "section-kept" },
  { code: "PLF.04.11.01", label: "Security Services", kind: "renumbered", storedCode: "PLF.04.10.01", via: "section-kept" },
  { code: "PLF.04.11.02", label: "Alarm Systems Maintenance", kind: "renumbered", storedCode: "PLF.04.10.02", via: "section-kept" },
  { code: "PLF.04.11.03", label: "Fire Safety Systems Maintenance", kind: "renumbered", storedCode: "PLF.04.10.03", via: "section-kept" },
  { code: "PLF.04.11.04", label: "Cleaning Expenses", kind: "renumbered", storedCode: "PLF.04.10.04", via: "section-kept" },
  { code: "PLF.04.11.98", label: "Other Security Expenses", kind: "renumbered", storedCode: "PLF.04.10.98", via: "section-kept" },
  { code: "PLF.04.11.99", label: "Other HSE Expenses", kind: "renumbered", storedCode: "PLF.04.10.99", via: "section-kept" },
  { code: "PLF.04.12.01", label: "Real Estate Insurance", kind: "renumbered", storedCode: "PLF.04.11.01", via: "section-kept" },
  { code: "PLF.04.12.99", label: "Other Insurance Fees", kind: "renumbered", storedCode: "PLF.04.11.99", via: "section-kept" },
  { code: "PLF.04.13.01", label: "Repairs of Buildings & Office", kind: "renumbered", storedCode: "PLF.04.12.01", via: "section-kept" },
  { code: "PLF.04.13.03", label: "Repairs of Office Furniture & Equipment", kind: "renumbered", storedCode: "PLF.04.12.03", via: "section-kept" },
  { code: "PLF.04.13.99", label: "Other Repair & Maintenance Expenses", kind: "renumbered", storedCode: "PLF.04.12.99", via: "section-kept" },
  { code: "PLF.04.14.01", label: "Bad Debt - Receivables", kind: "renumbered", storedCode: "PLF.04.13.01", via: "section-kept" },
  { code: "PLF.04.14.03", label: "Bad Debt - Prepayments", kind: "renumbered", storedCode: "PLF.04.13.02", via: "section-kept" },
  { code: "PLF.04.16.04", label: "Revaluation of Fixed & Intangible Assets", kind: "renumbered", storedCode: "PLF.05.13.01", via: "unique" },
  { code: "PLF.04.16.05", label: "Revaluation of Inventory", kind: "renumbered", storedCode: "PLF.05.13.02", via: "unique" },
  { code: "PLF.04.16.11", label: "Low Value Items Write-Off", kind: "renumbered", storedCode: "PLF.04.15.02", via: "section-kept" },
  { code: "PLF.04.16.98", label: "Revaluation of Other Assets", kind: "renumbered", storedCode: "PLF.04.15.99", via: "section-kept" },
  { code: "PLF.04.21.01", label: "Customs Duties", kind: "renumbered", storedCode: "PLF.04.02.03", via: "section-kept" },
  { code: "PLF.04.21.02", label: "Representative Expenses", kind: "renumbered", storedCode: "PLF.04.20.01", via: "section-kept" },
  { code: "PLF.04.21.99", label: "Other S&M Costs", kind: "renumbered", storedCode: "PLF.04.20.99", via: "unique" },
  { code: "PLF.05.01.03", label: "Staff Salaries, State Social Fund Fees", kind: "identical", storedCode: "PLF.05.01.03" },
  { code: "PLF.05.01.14", label: "Other Payroll Costs", kind: "renumbered", storedCode: "PLF.05.01.99", via: "section-kept" },
  { code: "PLF.05.01.25", label: "Voluntary Medical Insurance", kind: "renumbered", storedCode: "PLF.05.01.05", via: "section-kept" },
  { code: "PLF.05.01.26", label: "Obligatory Accident Insurance", kind: "renumbered", storedCode: "PLF.05.01.06", via: "section-kept" },
  { code: "PLF.05.01.27", label: "Entertainment Expenses", kind: "renumbered", storedCode: "PLF.05.01.07", via: "section-kept" },
  { code: "PLF.05.01.28", label: "Catering Expenses", kind: "renumbered", storedCode: "PLF.05.01.08", via: "section-kept" },
  { code: "PLF.05.02.99", label: "Business Trips Other Costs", kind: "identical", storedCode: "PLF.05.02.99" },
  { code: "PLF.05.03.01", label: "Audit Fees", kind: "identical", storedCode: "PLF.05.03.01" },
  { code: "PLF.05.03.02", label: "Consulting Fees & Due Diligence", kind: "renumbered", storedCode: "PLF.04.05.02", via: "unique" },
  { code: "PLF.05.03.03", label: "Legal & Notary Service Fees", kind: "renumbered", storedCode: "PLF.05.03.04", via: "section-kept" },
  { code: "PLF.05.03.04", label: "Brokerage Fees", kind: "renumbered", storedCode: "PLF.05.03.05", via: "section-kept" },
  { code: "PLF.05.03.99", label: "Other Professional Services", kind: "identical", storedCode: "PLF.05.03.99" },
  { code: "PLF.05.04.01", label: "Electricity Expenses", kind: "identical", storedCode: "PLF.05.04.01" },
  { code: "PLF.05.04.02", label: "Gas Expenses", kind: "identical", storedCode: "PLF.05.04.02" },
  { code: "PLF.05.04.03", label: "Heating Expenses", kind: "identical", storedCode: "PLF.05.04.03" },
  { code: "PLF.05.04.04", label: "Sewers Expenses", kind: "identical", storedCode: "PLF.05.04.04" },
  { code: "PLF.05.04.05", label: "Waste Disposal Expenses", kind: "identical", storedCode: "PLF.05.04.05" },
  { code: "PLF.05.04.06", label: "Water Expenses", kind: "identical", storedCode: "PLF.05.04.06" },
  { code: "PLF.05.04.07", label: "Landline Expenses", kind: "identical", storedCode: "PLF.05.04.07" },
  { code: "PLF.05.04.08", label: "Mobile Expenses", kind: "identical", storedCode: "PLF.05.04.08" },
  { code: "PLF.05.04.09", label: "Internet Expenses", kind: "identical", storedCode: "PLF.05.04.09" },
  { code: "PLF.05.04.10", label: "Postal and Courier Services", kind: "identical", storedCode: "PLF.05.04.10" },
  { code: "PLF.05.04.99", label: "Other Utilities & Communication Services", kind: "identical", storedCode: "PLF.05.04.99" },
  { code: "PLF.05.05.01", label: "Rent of Office & Administrative Buildings", kind: "identical", storedCode: "PLF.05.05.01" },
  { code: "PLF.05.05.02", label: "Rent of Warehouse", kind: "identical", storedCode: "PLF.05.05.02" },
  { code: "PLF.05.05.99", label: "Rent of Other Assets", kind: "identical", storedCode: "PLF.05.05.99" },
  { code: "PLF.05.06.01", label: "Office Supplies & Materials", kind: "identical", storedCode: "PLF.05.06.01" },
  { code: "PLF.05.06.02", label: "IT Expenses", kind: "identical", storedCode: "PLF.05.06.02" },
  { code: "PLF.05.06.99", label: "Other Office Expenses", kind: "identical", storedCode: "PLF.05.06.99" },
  { code: "PLF.05.07.01", label: "Fuel", kind: "identical", storedCode: "PLF.05.07.01" },
  { code: "PLF.05.07.02", label: "Vehicle Insurance", kind: "identical", storedCode: "PLF.05.07.02" },
  { code: "PLF.05.07.03", label: "Vehicle Repair & Maintenance", kind: "identical", storedCode: "PLF.05.07.03" },
  { code: "PLF.05.07.04", label: "Parking & Washing", kind: "identical", storedCode: "PLF.05.07.04" },
  { code: "PLF.05.07.99", label: "Other Transportation Expenses", kind: "identical", storedCode: "PLF.05.07.99" },
  { code: "PLF.05.08.01", label: "Security Services", kind: "identical", storedCode: "PLF.05.08.01" },
  { code: "PLF.05.08.02", label: "Alarm Systems Maintenance", kind: "identical", storedCode: "PLF.05.08.02" },
  { code: "PLF.05.08.03", label: "Fire Safety Systems Maintenance", kind: "identical", storedCode: "PLF.05.08.03" },
  { code: "PLF.05.08.04", label: "Cleaning Expenses", kind: "identical", storedCode: "PLF.05.08.04" },
  { code: "PLF.05.08.98", label: "Other Security Expenses", kind: "identical", storedCode: "PLF.05.08.98" },
  { code: "PLF.05.08.99", label: "Other HSE Expenses", kind: "identical", storedCode: "PLF.05.08.99" },
  { code: "PLF.05.09.01", label: "Real Estate Insurance", kind: "identical", storedCode: "PLF.05.09.01" },
  { code: "PLF.05.09.99", label: "Other Insurance Fees", kind: "identical", storedCode: "PLF.05.09.99" },
  { code: "PLF.05.10.01", label: "Repairs of Buildings & Office", kind: "identical", storedCode: "PLF.05.10.01" },
  { code: "PLF.05.10.02", label: "Repairs of Warehouse", kind: "renumbered", storedCode: "PLF.04.12.02", via: "unique" },
  { code: "PLF.05.10.03", label: "Repairs of Office Furniture & Equipment", kind: "renumbered", storedCode: "PLF.05.10.02", via: "section-kept" },
  { code: "PLF.05.10.99", label: "Other Repair & Maintenance Expenses", kind: "identical", storedCode: "PLF.05.10.99" },
  { code: "PLF.05.11.01", label: "Bad Debt - Receivables", kind: "identical", storedCode: "PLF.05.11.01" },
  { code: "PLF.05.11.03", label: "Bad Debt - Prepayments", kind: "renumbered", storedCode: "PLF.05.11.02", via: "section-kept" },
  { code: "PLF.05.12.01", label: "Simplified Tax Expense", kind: "identical", storedCode: "PLF.05.12.01" },
  { code: "PLF.05.12.02", label: "Property Tax Expense", kind: "identical", storedCode: "PLF.05.12.02" },
  { code: "PLF.05.12.03", label: "Excise Tax Expense", kind: "identical", storedCode: "PLF.05.12.03" },
  { code: "PLF.05.12.04", label: "Road Tax Expense", kind: "identical", storedCode: "PLF.05.12.04" },
  { code: "PLF.05.12.05", label: "Land Use Tax Expense", kind: "identical", storedCode: "PLF.05.12.05" },
  { code: "PLF.05.12.07", label: "Tax Penalties", kind: "identical", storedCode: "PLF.05.12.07" },
  { code: "PLF.05.12.97", label: "Other Tax Expenses", kind: "identical", storedCode: "PLF.05.12.97" },
  { code: "PLF.05.12.98", label: "Other Penalties", kind: "identical", storedCode: "PLF.05.12.98" },
  { code: "PLF.05.12.99", label: "Other Duties", kind: "identical", storedCode: "PLF.05.12.99" },
  { code: "PLF.05.13.04", label: "Revaluation of Fixed & Intangible Assets", kind: "renumbered", storedCode: "PLF.05.13.01", via: "unique" },
  { code: "PLF.05.13.05", label: "Revaluation of Inventory", kind: "renumbered", storedCode: "PLF.05.13.02", via: "unique" },
  { code: "PLF.05.13.11", label: "Low Value Items Write-Off", kind: "renumbered", storedCode: "PLF.05.13.04", via: "section-kept" },
  { code: "PLF.05.13.98", label: "Revaluation of Other Assets", kind: "renumbered", storedCode: "PLF.05.13.99", via: "section-kept" },
  { code: "PLF.05.18.01", label: "Bank Commission Fees", kind: "renumbered", storedCode: "PLF.05.15.01", via: "unique" },
  { code: "PLF.05.19.01", label: "Expenses on Disposal of Assets", kind: "renumbered", storedCode: "PLF.05.16.01", via: "unique" },
  { code: "PLF.05.19.02", label: "Charity & Donations", kind: "renumbered", storedCode: "PLF.05.16.02", via: "section-kept" },
  { code: "PLF.05.19.03", label: "Customs Duties", kind: "renumbered", storedCode: "PLF.05.16.03", via: "section-kept" },
  { code: "PLF.05.19.04", label: "Representative Expenses", kind: "renumbered", storedCode: "PLF.05.16.04", via: "section-kept" },
  { code: "PLF.05.19.05", label: "Gifts G&A", kind: "renumbered", storedCode: "PLF.05.16.05", via: "unique" },
  { code: "PLF.05.19.06", label: "Subscription Fees G&A", kind: "renumbered", storedCode: "PLF.05.16.06", via: "unique" },
  { code: "PLF.05.19.97", label: "Prior Year Expenses", kind: "renumbered", storedCode: "PLF.05.16.97", via: "unique" },
  { code: "PLF.05.19.99", label: "Other Operational Expenses", kind: "renumbered", storedCode: "PLF.05.16.99", via: "unique" },
  { code: "PLF.07.01.01", label: "Interest Income from Current Accounts & Deposits", kind: "identical", storedCode: "PLF.07.01.01" },
  { code: "PLF.07.01.99", label: "Other Interest Income", kind: "identical", storedCode: "PLF.07.01.99" },
  { code: "PLF.07.02.03", label: "Share of Profit of Joint Ventures", kind: "renumbered", storedCode: "PLF.07.02.01", via: "unique" },
  { code: "PLF.07.02.04", label: "Subsidies - Farming", kind: "renumbered", storedCode: "PLF.07.02.02", via: "unique" },
  { code: "PLF.07.02.99", label: "Other Non-Operating Income", kind: "identical", storedCode: "PLF.07.02.99" },
  { code: "PLF.07.03.02", label: "Production downtime", kind: "renumbered", storedCode: "PLF.07.03.01", via: "unique" },
  { code: "PLF.07.03.99", label: "Other Non-Operating Expense", kind: "identical", storedCode: "PLF.07.03.99" },
  { code: "PLF.07.04.02", label: "Gain/Loss on Sale of Intangible Assets", kind: "identical", storedCode: "PLF.07.04.02" },
  { code: "PLF.07.04.99", label: "Gain/Loss on Sale of Other Assets", kind: "identical", storedCode: "PLF.07.04.99" },
  { code: "PLF.08.01", label: "Shareholders' expense", kind: "renumbered", storedCode: "PLF.09.01", via: "unique" },
  { code: "PLF.05.16.01", label: "Interest Expense on Bank Loans & Overdrafts", kind: "renumbered", storedCode: "PLF.09.02.01", via: "unique" },
  { code: "PLF.05.16.02", label: "Interest Expense on Finance Lease", kind: "renumbered", storedCode: "PLF.09.02.02", via: "unique" },
  { code: "PLF.05.16.03", label: "Interest Expense on Shareholder Loans", kind: "renumbered", storedCode: "PLF.09.02.03", via: "unique" },
  { code: "PLF.05.16.99", label: "Other Interest Expense", kind: "renumbered", storedCode: "PLF.09.02.99", via: "unique" },
  { code: "PLF.05.15.01", label: "Depreciation - Buildings", kind: "renumbered", storedCode: "PLF.09.03.01", via: "unique" },
  { code: "PLF.05.15.02", label: "Depreciation - Leasehold Improvements", kind: "renumbered", storedCode: "PLF.09.03.02", via: "unique" },
  { code: "PLF.05.15.03", label: "Depreciation - Vehicles", kind: "renumbered", storedCode: "PLF.09.03.03", via: "unique" },
  { code: "PLF.05.15.04", label: "Depreciation - Office Equipment & Furniture", kind: "renumbered", storedCode: "PLF.09.03.04", via: "unique" },
  { code: "PLF.05.15.05", label: "Amortization - Computer Software & Websites", kind: "renumbered", storedCode: "PLF.09.03.05", via: "unique" },
  { code: "PLF.05.15.06", label: "Amortization - Licenses", kind: "renumbered", storedCode: "PLF.09.03.06", via: "unique" },
  { code: "PLF.05.15.07", label: "Amortization - Patents & Copyrights", kind: "renumbered", storedCode: "PLF.09.03.07", via: "unique" },
  { code: "PLF.05.15.08", label: "Amortization - Branding, Franchises & Trademarks", kind: "renumbered", storedCode: "PLF.09.03.08", via: "unique" },
  { code: "PLF.05.15.98", label: "Depreciation - Other Tangible Assets", kind: "renumbered", storedCode: "PLF.09.03.98", via: "unique" },
  { code: "PLF.05.15.99", label: "Amortization - Other intangibles", kind: "renumbered", storedCode: "PLF.09.03.99", via: "unique" },
  { code: "PLF.09.01.01", label: "Profit Tax", kind: "renumbered", storedCode: "PLF.09.04.01", via: "unique" },
  { code: "PLF.09.01.02", label: "Profit Tax - Accrued", kind: "renumbered", storedCode: "PLF.09.04.02", via: "unique" },
  { code: "PLF.01.01.01", label: "Revenue from Sale of Wheat", kind: "identical", storedCode: "PLF.01.01.01" },
  { code: "PLF.01.01.02", label: "Revenue from Sale of Sugar Beet", kind: "identical", storedCode: "PLF.01.01.02" },
  { code: "PLF.01.01.03", label: "Revenue from Sale of Corn", kind: "identical", storedCode: "PLF.01.01.03" },
  { code: "PLF.01.01.04", label: "Revenue from Sale of Barley", kind: "identical", storedCode: "PLF.01.01.04" },
  { code: "PLF.01.01.05", label: "Revenue from Sale of Cotton", kind: "identical", storedCode: "PLF.01.01.05" },
  { code: "PLF.01.02.01", label: "Revenue from Rent of Land", kind: "renumbered", storedCode: "PLF.01.03.01", via: "unique" },
  { code: "PLF.01.02.02", label: "Revenue from Laboratory Services", kind: "renumbered", storedCode: "PLF.01.03.02", via: "unique" },
  { code: "PLF.01.02.99", label: "Revenue from Other Sources", kind: "renumbered", storedCode: "PLF.01.03.99", via: "unique" },
  { code: "PLF.02.01.01", label: "Wheat Costs", kind: "identical", storedCode: "PLF.02.01.01" },
  { code: "PLF.02.01.02", label: "Sugar Beet Costs", kind: "identical", storedCode: "PLF.02.01.02" },
  { code: "PLF.02.01.03", label: "Corn Costs", kind: "identical", storedCode: "PLF.02.01.03" },
  { code: "PLF.02.01.04", label: "Barley Costs", kind: "identical", storedCode: "PLF.02.01.04" },
  { code: "PLF.02.01.05", label: "Cotton Costs", kind: "identical", storedCode: "PLF.02.01.05" },
  { code: "PLF.02.02.01", label: "Cost of Rent", kind: "renumbered", storedCode: "PLF.02.03.01", via: "unique" },
  { code: "PLF.02.02.02", label: "Cost of Laboratory Services", kind: "renumbered", storedCode: "PLF.02.03.02", via: "unique" },
  { code: "PLF.02.02.99", label: "Other Costs", kind: "renumbered", storedCode: "PLF.02.03.99", via: "unique" },
  { code: "PLF.05.01.R", label: "Personnel Costs - G&A", kind: "identical", storedCode: "PLF.05.01.R" },
  { code: "PLF.05.02.R", label: "Business Trips - G&A", kind: "identical", storedCode: "PLF.05.02.R" },
  { code: "PLF.05.03.R", label: "Professional Services Fees - G&A", kind: "identical", storedCode: "PLF.05.03.R" },
  { code: "PLF.05.04.R", label: "Utilities & Communication - G&A", kind: "identical", storedCode: "PLF.05.04.R" },
  { code: "PLF.05.05.R", label: "Rent Expense - G&A", kind: "identical", storedCode: "PLF.05.05.R" },
  { code: "PLF.05.06.R", label: "Office & IT Expenses - G&A", kind: "identical", storedCode: "PLF.05.06.R" },
  { code: "PLF.05.07.R", label: "Transportation Expenses - G&A", kind: "identical", storedCode: "PLF.05.07.R" },
  { code: "PLF.05.08.R", label: "Security, HSE & Cleaning Expenses - G&A", kind: "identical", storedCode: "PLF.05.08.R" },
  { code: "PLF.05.09.R", label: "Insurance Fees - G&A", kind: "identical", storedCode: "PLF.05.09.R" },
  { code: "PLF.05.10.R", label: "Repairs & Maintenance - G&A", kind: "identical", storedCode: "PLF.05.10.R" },
  { code: "PLF.05.12.R", label: "Taxes, Penalties & Other Duties - G&A", kind: "identical", storedCode: "PLF.05.12.R" },
  { code: "PLF.05.13.R", label: "Revaluation & Impairment - G&A", kind: "identical", storedCode: "PLF.05.13.R" },
  { code: "PLF.05.19.R", label: "Other G&A Expense", kind: "identical", storedCode: "PLF.05.19.R" },
  { code: "PLF.12.03.01", label: "Unused Vacations Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.01", via: "unique" },
  { code: "PLF.12.03.02", label: "Annual Bonus Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.02", via: "unique" },
  { code: "PLF.12.03.04", label: "Receivable Allowance Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.04", via: "unique" },
  { code: "PLF.12.03.05", label: "Prepayment Allowance Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.05", via: "unique" },
  { code: "PLF.12.03.06", label: "Inventory Impairment Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.06", via: "unique" },
  { code: "PLF.12.03.07", label: "Legal Dispute Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.08", via: "unique" },
  { code: "PLF.12.03.08", label: "Expense Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.09", via: "unique" },
  { code: "PLF.12.03.99", label: "Other Provision - G&A", kind: "renumbered", storedCode: "PLF.12.01.99", via: "unique" },
  { code: "PLF.07.02.04", label: "Subsidies - Investment", kind: "renumbered", storedCode: "PLF.07.02.03", via: "unique" },
  { code: "PLF.07.02.04", label: "Subsidies - Product", kind: "identical", storedCode: "PLF.07.02.04" },
  { code: "PLF.05.15.09", label: "Depreciation - Machinery & Equipment", kind: "renumbered", storedCode: "PLF.09.03.09", via: "unique" },
  { code: "PLF.01.01.99", label: "Revenue from Other Sources", kind: "renumbered", storedCode: "PLF.01.01.99", via: "override", overrideReason: "An elimination row the workbook mislabelled. It sits at PLF.01.01.99 and is paired with PLF.02.01.99 in the elimination block, like every other pair there; the three company blocks call the same code \"Revenue from Sale of Other Products\". Read by its label it landed in other sources, taking 705,200 of elimination away from the branch it belongs to and turning that branch's revenue negative — which is what printed +277.3% on a line that lost money." },
  { code: "PLF.01.01.06", label: "Revenue from Sale of Processed Corn Products", kind: "own_account", storedCode: "PLF.01.01.06.FY2025", mintedBecause: "the current chart names PLF.01.01.06 \"Revenue from Sale of Almond\"" },
  { code: "PLF.01.02.03", label: "Revenue from Management Services", kind: "own_account", storedCode: "PLF.01.02.03.FY2025", mintedBecause: "the current chart names PLF.01.02.03 \"Revenue from Sale of Fructose\"" },
  { code: "PLF.01.10.01", label: "Sales Return", kind: "own_account", storedCode: "PLF.01.10.01" },
  { code: "PLF.01.10.02", label: "Discounts", kind: "own_account", storedCode: "PLF.01.10.02" },
  { code: "PLF.02.01.06", label: "Processed Corn Products", kind: "own_account", storedCode: "PLF.02.01.06.FY2025", mintedBecause: "the current chart names PLF.02.01.06 \"Almond Costs\"" },
  { code: "PLF.04.01.01", label: "Advertisement in TV", kind: "own_account", storedCode: "PLF.04.01.01.FY2025", mintedBecause: "the current chart names PLF.04.01.01 \"Subscription Fee\"" },
  { code: "PLF.04.01.02", label: "Advertisement in Press", kind: "own_account", storedCode: "PLF.04.01.02.FY2025", mintedBecause: "the current chart names PLF.04.01.02 \"Participation in Forums & Exhibitions\"" },
  { code: "PLF.04.01.03", label: "Advertisement in Internet", kind: "own_account", storedCode: "PLF.04.01.03.FY2025", mintedBecause: "the current chart names PLF.04.01.03 \"Promotional Gifts\"" },
  { code: "PLF.04.01.04", label: "Advertisement on Vehicles", kind: "own_account", storedCode: "PLF.04.01.04.FY2025", mintedBecause: "the current chart names PLF.04.01.04 \"Charity & Donations\"" },
  { code: "PLF.04.01.05", label: "Advertisement on Buildings", kind: "own_account", storedCode: "PLF.04.01.05.FY2025", mintedBecause: "the current chart names PLF.04.01.05 \"Meeting with Potential Clients\"" },
  { code: "PLF.04.01.99", label: "Other Advertisements", kind: "own_account", storedCode: "PLF.04.01.99.FY2025", mintedBecause: "the current chart names PLF.04.01.99 \"Other Promotional & Research Expenses\"" },
  { code: "PLF.04.02.03", label: "Gifts", kind: "own_account", storedCode: "PLF.04.02.03.FY2025", mintedBecause: "the current chart names PLF.04.02.03 \"Customs Duties\"" },
  { code: "PLF.04.04.01", label: "Staff Salaries, Net", kind: "own_account", storedCode: "PLF.04.04.01.FY2025", mintedBecause: "the current chart names PLF.04.04.01 \"Local Business Trips\"" },
  { code: "PLF.04.04.02", label: "Staff Salaries, Personal Income Tax", kind: "own_account", storedCode: "PLF.04.04.02.FY2025", mintedBecause: "the current chart names PLF.04.04.02 \"Foreign Business Trips\"" },
  { code: "PLF.04.04.04", label: "Staff Salaries, Trade Union Fees", kind: "own_account", storedCode: "PLF.04.04.04" },
  { code: "PLF.04.04.05", label: "Contracted Employees Salaries, Net", kind: "own_account", storedCode: "PLF.04.04.05" },
  { code: "PLF.04.04.06", label: "Contracted Employees Salaries, Tax", kind: "own_account", storedCode: "PLF.04.04.06" },
  { code: "PLF.04.04.07", label: "Contracted Employees Salaries, State Social Fund Fees", kind: "own_account", storedCode: "PLF.04.04.07" },
  { code: "PLF.04.04.08", label: "Overtimes, Net", kind: "own_account", storedCode: "PLF.04.04.08" },
  { code: "PLF.04.04.09", label: "Overtimes, Personal Income Tax", kind: "own_account", storedCode: "PLF.04.04.09" },
  { code: "PLF.04.04.10", label: "Overtimes, State Social Fund Fees", kind: "own_account", storedCode: "PLF.04.04.10" },
  { code: "PLF.04.04.11", label: "Bonuses, Net", kind: "own_account", storedCode: "PLF.04.04.11" },
  { code: "PLF.04.04.12", label: "Bonuses, Personal Income Tax", kind: "own_account", storedCode: "PLF.04.04.12" },
  { code: "PLF.04.04.13", label: "Bonuses, State Social Fund Fees", kind: "own_account", storedCode: "PLF.04.04.13" },
  { code: "PLF.04.04.15", label: "Local Trainings Cost", kind: "own_account", storedCode: "PLF.04.04.15" },
  { code: "PLF.04.04.16", label: "Local Trainings Accomodation", kind: "own_account", storedCode: "PLF.04.04.16" },
  { code: "PLF.04.04.17", label: "Local Trainings Travel", kind: "own_account", storedCode: "PLF.04.04.17" },
  { code: "PLF.04.04.18", label: "Local Trainings Per Diem", kind: "own_account", storedCode: "PLF.04.04.18" },
  { code: "PLF.04.04.19", label: "Local Trainings Other Costs", kind: "own_account", storedCode: "PLF.04.04.19" },
  { code: "PLF.04.04.20", label: "Abroad Trainings Cost", kind: "own_account", storedCode: "PLF.04.04.20" },
  { code: "PLF.04.04.21", label: "Abroad Trainings Accomodation", kind: "own_account", storedCode: "PLF.04.04.21" },
  { code: "PLF.04.04.22", label: "Abroad Trainings Travel", kind: "own_account", storedCode: "PLF.04.04.22" },
  { code: "PLF.04.04.23", label: "Abroad Trainings Per Diem", kind: "own_account", storedCode: "PLF.04.04.23" },
  { code: "PLF.04.04.24", label: "Abroad Trainings Other Costs", kind: "own_account", storedCode: "PLF.04.04.24" },
  { code: "PLF.04.04.97", label: "Other Payments to Staff", kind: "own_account", storedCode: "PLF.04.04.97" },
  { code: "PLF.04.04.98", label: "Other Payments to Contracted Employees", kind: "own_account", storedCode: "PLF.04.04.98" },
  { code: "PLF.04.04.99", label: "Other Extraordinary Personnel Costs", kind: "own_account", storedCode: "PLF.04.04.99.FY2025", mintedBecause: "the current chart names PLF.04.04.99 \"Business Trips Other Costs\"" },
  { code: "PLF.04.05.01", label: "Business Trips Accomodation", kind: "own_account", storedCode: "PLF.04.05.01.FY2025", mintedBecause: "the current chart names PLF.04.05.01 \"Audit Fees\"" },
  { code: "PLF.04.05.02", label: "Business Trips Travel", kind: "own_account", storedCode: "PLF.04.05.02.FY2025", mintedBecause: "the current chart names PLF.04.05.02 \"Consulting Fees & Due Diligence\"" },
  { code: "PLF.04.05.03", label: "Business Trips Per Diem", kind: "own_account", storedCode: "PLF.04.05.03.FY2025", mintedBecause: "the current chart names PLF.04.05.03 \"Legal & Notary Service Fees\"" },
  { code: "PLF.04.06.05", label: "Asset Management Fees", kind: "own_account", storedCode: "PLF.04.06.05.FY2025", mintedBecause: "the current chart names PLF.04.06.05 \"Waste Disposal Expenses\"" },
  { code: "PLF.04.06.06", label: "Property Valuation Expense", kind: "own_account", storedCode: "PLF.04.06.06.FY2025", mintedBecause: "the current chart names PLF.04.06.06 \"Water Expenses\"" },
  { code: "PLF.04.06.07", label: "Expertise of Building Structures & Material Quality", kind: "own_account", storedCode: "PLF.04.06.07.FY2025", mintedBecause: "the current chart names PLF.04.06.07 \"Landline Expenses\"" },
  { code: "PLF.04.06.08", label: "Architectural Services", kind: "own_account", storedCode: "PLF.04.06.08.FY2025", mintedBecause: "the current chart names PLF.04.06.08 \"Mobile Expenses\"" },
  { code: "PLF.04.06.09", label: "Export Certification", kind: "own_account", storedCode: "PLF.04.06.09.FY2025", mintedBecause: "the current chart names PLF.04.06.09 \"Internet Expenses\"" },
  { code: "PLF.04.08.02", label: "Rent of Sales & Service Points", kind: "own_account", storedCode: "PLF.04.08.02.FY2025", mintedBecause: "the current chart names PLF.04.08.02 \"IT Expenses\"" },
  { code: "PLF.04.08.98", label: "Rent of Other Areas", kind: "own_account", storedCode: "PLF.04.08.98" },
  { code: "PLF.04.13.02", label: "Repairs of Sales & Service Centers", kind: "own_account", storedCode: "PLF.04.13.02.FY2025", mintedBecause: "the current chart names PLF.04.13.02 \"Bad Debt - Prepayments\"" },
  { code: "PLF.04.14.02", label: "Bad Debt - Loans Issued", kind: "own_account", storedCode: "PLF.04.14.02" },
  { code: "PLF.04.16.01", label: "Revaluation of Investment Property", kind: "own_account", storedCode: "PLF.04.16.01" },
  { code: "PLF.04.16.02", label: "Revaluation of Investments Held to Maturity", kind: "own_account", storedCode: "PLF.04.16.02" },
  { code: "PLF.04.16.03", label: "Revaluation of Securities & Derivatives", kind: "own_account", storedCode: "PLF.04.16.03" },
  { code: "PLF.04.16.06", label: "Impairment of Investment Property", kind: "own_account", storedCode: "PLF.04.16.06" },
  { code: "PLF.04.16.07", label: "Impairment of Investments Held to Maturity", kind: "own_account", storedCode: "PLF.04.16.07" },
  { code: "PLF.04.16.08", label: "Impairment of Goodwill", kind: "own_account", storedCode: "PLF.04.16.08" },
  { code: "PLF.04.16.09", label: "Impairment of Fixed & Intangible Assets", kind: "own_account", storedCode: "PLF.04.16.09" },
  { code: "PLF.04.16.10", label: "Impairment of Inventory", kind: "own_account", storedCode: "PLF.04.16.10" },
  { code: "PLF.04.16.99", label: "Impairment of Other Assets", kind: "own_account", storedCode: "PLF.04.16.99" },
  { code: "PLF.05.01.01", label: "Staff Salaries, Net", kind: "own_account", storedCode: "PLF.05.01.01.FY2025", mintedBecause: "the current chart names PLF.05.01.01 \"Staff Salaries, Gross\"" },
  { code: "PLF.05.01.02", label: "Staff Salaries, Personal Income Tax", kind: "own_account", storedCode: "PLF.05.01.02.FY2025", mintedBecause: "the current chart names PLF.05.01.02 \"Bonuses, Gross\"" },
  { code: "PLF.05.01.04", label: "Staff Salaries, Trade Union Fees", kind: "own_account", storedCode: "PLF.05.01.04.FY2025", mintedBecause: "the current chart names PLF.05.01.04 \"Employee Training Costs\"" },
  { code: "PLF.05.01.05", label: "Contracted Employees Salaries, Net", kind: "own_account", storedCode: "PLF.05.01.05.FY2025", mintedBecause: "the current chart names PLF.05.01.05 \"Voluntary Medical Insurance\"" },
  { code: "PLF.05.01.06", label: "Contracted Employees Salaries, Tax", kind: "own_account", storedCode: "PLF.05.01.06.FY2025", mintedBecause: "the current chart names PLF.05.01.06 \"Obligatory Accident Insurance\"" },
  { code: "PLF.05.01.07", label: "Contracted Employees Salaries, State Social Fund Fees", kind: "own_account", storedCode: "PLF.05.01.07.FY2025", mintedBecause: "the current chart names PLF.05.01.07 \"Entertainment Expenses\"" },
  { code: "PLF.05.01.08", label: "Overtimes, Net", kind: "own_account", storedCode: "PLF.05.01.08.FY2025", mintedBecause: "the current chart names PLF.05.01.08 \"Catering Expenses\"" },
  { code: "PLF.05.01.09", label: "Overtimes, Personal Income Tax", kind: "own_account", storedCode: "PLF.05.01.09.FY2025", mintedBecause: "the current chart names PLF.05.01.09 \"Employee Transportation Costs\"" },
  { code: "PLF.05.01.10", label: "Overtimes, State Social Fund Fees", kind: "own_account", storedCode: "PLF.05.01.10.FY2025", mintedBecause: "the current chart names PLF.05.01.10 \"Accomodation Expenses\"" },
  { code: "PLF.05.01.11", label: "Bonuses, Net", kind: "own_account", storedCode: "PLF.05.01.11" },
  { code: "PLF.05.01.12", label: "Bonuses, Personal Income Tax", kind: "own_account", storedCode: "PLF.05.01.12" },
  { code: "PLF.05.01.13", label: "Bonuses, State Social Fund Fees", kind: "own_account", storedCode: "PLF.05.01.13" },
  { code: "PLF.05.01.15", label: "Local Trainings Cost", kind: "own_account", storedCode: "PLF.05.01.15" },
  { code: "PLF.05.01.16", label: "Local Trainings Accomodation", kind: "own_account", storedCode: "PLF.05.01.16" },
  { code: "PLF.05.01.17", label: "Local Trainings Travel", kind: "own_account", storedCode: "PLF.05.01.17" },
  { code: "PLF.05.01.18", label: "Local Trainings Per Diem", kind: "own_account", storedCode: "PLF.05.01.18" },
  { code: "PLF.05.01.19", label: "Local Trainings Other Costs", kind: "own_account", storedCode: "PLF.05.01.19" },
  { code: "PLF.05.01.20", label: "Abroad Trainings Cost", kind: "own_account", storedCode: "PLF.05.01.20" },
  { code: "PLF.05.01.21", label: "Abroad Trainings Accomodation", kind: "own_account", storedCode: "PLF.05.01.21" },
  { code: "PLF.05.01.22", label: "Abroad Trainings Travel", kind: "own_account", storedCode: "PLF.05.01.22" },
  { code: "PLF.05.01.23", label: "Abroad Trainings Per Diem", kind: "own_account", storedCode: "PLF.05.01.23" },
  { code: "PLF.05.01.24", label: "Abroad Trainings Other Costs", kind: "own_account", storedCode: "PLF.05.01.24" },
  { code: "PLF.05.01.97", label: "Other Payments to Staff", kind: "own_account", storedCode: "PLF.05.01.97" },
  { code: "PLF.05.01.98", label: "Other Payments to Contracted Employees", kind: "own_account", storedCode: "PLF.05.01.98" },
  { code: "PLF.05.01.99", label: "Other Extraordinary Personnel Costs", kind: "own_account", storedCode: "PLF.05.01.99.FY2025", mintedBecause: "the current chart names PLF.05.01.99 \"Other Payroll Costs\"" },
  { code: "PLF.05.02.01", label: "Business Trips Accomodation", kind: "own_account", storedCode: "PLF.05.02.01.FY2025", mintedBecause: "the current chart names PLF.05.02.01 \"Local Business Trips\"" },
  { code: "PLF.05.02.02", label: "Business Trips Travel", kind: "own_account", storedCode: "PLF.05.02.02.FY2025", mintedBecause: "the current chart names PLF.05.02.02 \"Foreign Business Trips\"" },
  { code: "PLF.05.02.03", label: "Business Trips Per Diem", kind: "own_account", storedCode: "PLF.05.02.03" },
  { code: "PLF.05.03.05", label: "Asset Management Fees", kind: "own_account", storedCode: "PLF.05.03.05.FY2025", mintedBecause: "the current chart names PLF.05.03.05 \"Brokerage Fees\"" },
  { code: "PLF.05.03.06", label: "Property Valuation Expense", kind: "own_account", storedCode: "PLF.05.03.06.FY2025", mintedBecause: "the current chart names PLF.05.03.06 \"Assets Valuation Expense\"" },
  { code: "PLF.05.03.07", label: "Expertise of Building Structures & Material Quality", kind: "own_account", storedCode: "PLF.05.03.07.FY2025", mintedBecause: "the current chart names PLF.05.03.07 \"Certification Services\"" },
  { code: "PLF.05.03.08", label: "Architectural Services", kind: "own_account", storedCode: "PLF.05.03.08" },
  { code: "PLF.05.03.09", label: "Export Certification", kind: "own_account", storedCode: "PLF.05.03.09" },
  { code: "PLF.05.03.10", label: "Management Fees", kind: "own_account", storedCode: "PLF.05.03.10" },
  { code: "PLF.05.05.98", label: "Rent of Other Areas", kind: "own_account", storedCode: "PLF.05.05.98" },
  { code: "PLF.05.11.02", label: "Bad Debt - Loans Issued", kind: "own_account", storedCode: "PLF.05.11.02.FY2025", mintedBecause: "the current chart names PLF.05.11.02 \"Bad Debt - Prepayments\"" },
  { code: "PLF.05.12.06", label: "Mining Tax Expense", kind: "own_account", storedCode: "PLF.05.12.06.FY2025", mintedBecause: "the current chart names PLF.05.12.06 \"Non-Recoverable VAT Expense\"" },
  { code: "PLF.05.13.01", label: "Revaluation of Investment Property", kind: "own_account", storedCode: "PLF.05.13.01.FY2025", mintedBecause: "the current chart names PLF.05.13.01 \"Revaluation of Fixed & Intangible Assets\"" },
  { code: "PLF.05.13.02", label: "Revaluation of Investments Held to Maturity", kind: "own_account", storedCode: "PLF.05.13.02.FY2025", mintedBecause: "the current chart names PLF.05.13.02 \"Revaluation of Inventory\"" },
  { code: "PLF.05.13.03", label: "Revaluation of Securities & Derivatives", kind: "own_account", storedCode: "PLF.05.13.03.FY2025", mintedBecause: "the current chart names PLF.05.13.03 \"Revaluation of Goodwill\"" },
  { code: "PLF.05.13.06", label: "Impairment of Investment Property", kind: "own_account", storedCode: "PLF.05.13.06" },
  { code: "PLF.05.13.07", label: "Impairment of Investments Held to Maturity", kind: "own_account", storedCode: "PLF.05.13.07" },
  { code: "PLF.05.13.08", label: "Impairment of Goodwill", kind: "own_account", storedCode: "PLF.05.13.08" },
  { code: "PLF.05.13.09", label: "Impairment of Fixed & Intangible Assets", kind: "own_account", storedCode: "PLF.05.13.09" },
  { code: "PLF.05.13.10", label: "Impairment of Inventory", kind: "own_account", storedCode: "PLF.05.13.10" },
  { code: "PLF.05.13.99", label: "Impairment of Other Assets", kind: "own_account", storedCode: "PLF.05.13.99.FY2025", mintedBecause: "the current chart names PLF.05.13.99 \"Revaluation of Other Assets\"" },
  { code: "PLF.05.17.01", label: "Realized FX Gain/Loss", kind: "own_account", storedCode: "PLF.05.17.01" },
  { code: "PLF.05.17.02", label: "Unrealized FX Gain/Loss from Revaluation of Foreign Currency Balances", kind: "own_account", storedCode: "PLF.05.17.02" },
  { code: "PLF.05.19.98", label: "Income/Expenses from Discontinued Operations", kind: "own_account", storedCode: "PLF.05.19.98" },
  { code: "PLF.12.01.01", label: "Unused Vacations Accrual - CoGS", kind: "own_account", storedCode: "PLF.12.01.01.FY2025", mintedBecause: "the current chart names PLF.12.01.01 \"Unused Vacations Provision - G&A\"" },
  { code: "PLF.12.01.02", label: "Annual Bonus Accrual - CoGS", kind: "own_account", storedCode: "PLF.12.01.02.FY2025", mintedBecause: "the current chart names PLF.12.01.02 \"Annual Bonus Provision - G&A\"" },
  { code: "PLF.12.01.03", label: "Contingent Tax Liabilities Accrual - CoGS", kind: "own_account", storedCode: "PLF.12.01.03.FY2025", mintedBecause: "the current chart names PLF.12.01.03 \"Tax Liabilities Provision - G&A\"" },
  { code: "PLF.12.01.04", label: "Receivable Allowance Accrual - CoGS", kind: "own_account", storedCode: "PLF.12.01.04.FY2025", mintedBecause: "the current chart names PLF.12.01.04 \"Receivable Allowance Provision - G&A\"" },
  { code: "PLF.12.01.05", label: "Prepayment Allowance Accrual - CoGS", kind: "own_account", storedCode: "PLF.12.01.05.FY2025", mintedBecause: "the current chart names PLF.12.01.05 \"Prepayment Allowance Provision - G&A\"" },
  { code: "PLF.12.01.06", label: "Inventory Impairment Accrual - CoGS", kind: "own_account", storedCode: "PLF.12.01.06.FY2025", mintedBecause: "the current chart names PLF.12.01.06 \"Inventory Impairment Provision - G&A\"" },
  { code: "PLF.12.01.07", label: "Legal Dispute Accrual - CoGS", kind: "own_account", storedCode: "PLF.12.01.07.FY2025", mintedBecause: "the current chart names PLF.12.01.07 \"Finished Goods Impairment Provision - G&A\"" },
  { code: "PLF.12.01.08", label: "Expense Accruals - CoGS", kind: "own_account", storedCode: "PLF.12.01.08.FY2025", mintedBecause: "the current chart names PLF.12.01.08 \"Legal Dispute Provision - G&A\"" },
  { code: "PLF.12.01.99", label: "Other Accruals - CoGS", kind: "own_account", storedCode: "PLF.12.01.99.FY2025", mintedBecause: "the current chart names PLF.12.01.99 \"Other Provision - G&A\"" },
  { code: "PLF.12.02.01", label: "Unused Vacations Accrual - S&M", kind: "own_account", storedCode: "PLF.12.02.01" },
  { code: "PLF.12.02.02", label: "Annual Bonus Accrual - S&M", kind: "own_account", storedCode: "PLF.12.02.02" },
  { code: "PLF.12.02.03", label: "Contingent Tax Liabilities Accrual - S&M", kind: "own_account", storedCode: "PLF.12.02.03" },
  { code: "PLF.12.02.04", label: "Receivable Allowance Accrual - S&M", kind: "own_account", storedCode: "PLF.12.02.04" },
  { code: "PLF.12.02.05", label: "Prepayment Allowance Accrual - S&M", kind: "own_account", storedCode: "PLF.12.02.05" },
  { code: "PLF.12.02.06", label: "Inventory Impairment Accrual - S&M", kind: "own_account", storedCode: "PLF.12.02.06" },
  { code: "PLF.12.02.07", label: "Legal Dispute Accrual - S&M", kind: "own_account", storedCode: "PLF.12.02.07" },
  { code: "PLF.12.02.08", label: "Expense Accruals - S&M", kind: "own_account", storedCode: "PLF.12.02.08" },
  { code: "PLF.12.02.99", label: "Other Accruals - S&M", kind: "own_account", storedCode: "PLF.12.02.99" },
  { code: "PLF.12.03.01", label: "Unused Vacations Accrual - G&A", kind: "own_account", storedCode: "PLF.12.03.01" },
  { code: "PLF.12.03.02", label: "Annual Bonus Accrual - G&A", kind: "own_account", storedCode: "PLF.12.03.02" },
  { code: "PLF.12.03.03", label: "Contingent Tax Liabilities Accrual - G&A", kind: "own_account", storedCode: "PLF.12.03.03" },
  { code: "PLF.12.03.04", label: "Receivable Allowance Accrual - G&A", kind: "own_account", storedCode: "PLF.12.03.04" },
  { code: "PLF.12.03.05", label: "Prepayment Allowance Accrual - G&A", kind: "own_account", storedCode: "PLF.12.03.05" },
  { code: "PLF.12.03.06", label: "Inventory Impairment Accrual - G&A", kind: "own_account", storedCode: "PLF.12.03.06" },
  { code: "PLF.12.03.07", label: "Legal Dispute Accrual - G&A", kind: "own_account", storedCode: "PLF.12.03.07" },
  { code: "PLF.12.03.08", label: "Expense Accruals - G&A", kind: "own_account", storedCode: "PLF.12.03.08" },
  { code: "PLF.12.03.99", label: "Other Accruals - G&A", kind: "own_account", storedCode: "PLF.12.03.99" },
  { code: "PLF.07.01.02", label: "Interest Income from Loans Issued", kind: "own_account", storedCode: "PLF.07.01.02" },
  { code: "PLF.07.01.03", label: "Interest Income from Securities", kind: "own_account", storedCode: "PLF.07.01.03" },
  { code: "PLF.07.01.04", label: "Interest Income from Finance Leasing", kind: "own_account", storedCode: "PLF.07.01.04" },
  { code: "PLF.07.02.01", label: "Share of Profit of Subsidiaries", kind: "own_account", storedCode: "PLF.07.02.01.FY2025", mintedBecause: "the current chart names PLF.07.02.01 \"Share of Profit of Joint Ventures\"" },
  { code: "PLF.07.02.02", label: "Share of Profit of Associates", kind: "own_account", storedCode: "PLF.07.02.02.FY2025", mintedBecause: "the current chart names PLF.07.02.02 \"Subsidies - Farming\"" },
  { code: "PLF.07.03.01", label: "Reserve for Future Capital Investments", kind: "own_account", storedCode: "PLF.07.03.01.FY2025", mintedBecause: "the current chart names PLF.07.03.01 \"Production downtime\"" },
  { code: "PLF.07.04.01", label: "Gain/Loss on Sale of Property & Equipment", kind: "own_account", storedCode: "PLF.07.04.01.FY2025", mintedBecause: "the current chart names PLF.07.04.01 \"Gain/Loss on Sale of Tangible Assets\"" },
  { code: "PLF.07.04.03", label: "Gain/Loss on Sale of Investments Available for Sale", kind: "own_account", storedCode: "PLF.07.04.03" },
  { code: "PLF.05.16.04", label: "Interest Expense on Derivatives", kind: "own_account", storedCode: "PLF.05.16.04.FY2025", mintedBecause: "the current chart names PLF.05.16.04 \"Representative Expenses\"" },
  { code: "PLF.05.16.05", label: "Unwinding of Discounts", kind: "own_account", storedCode: "PLF.05.16.05.FY2025", mintedBecause: "the current chart names PLF.05.16.05 \"Gifts G&A\"" },
  { code: "PLF.09.02.01", label: "Deferred Tax from Temporary Differences", kind: "own_account", storedCode: "PLF.09.02.01.FY2025", mintedBecause: "the current chart names PLF.09.02.01 \"Interest Expense on Bank Loans & Overdrafts\"" },
  { code: "PLF.09.02.02", label: "Deferred Tax from Accumulated Loss", kind: "own_account", storedCode: "PLF.09.02.02.FY2025", mintedBecause: "the current chart names PLF.09.02.02 \"Interest Expense on Finance Lease\"" },
  { code: "PLF.09.02.03", label: "Deferred Tax Impairment", kind: "own_account", storedCode: "PLF.09.02.03.FY2025", mintedBecause: "the current chart names PLF.09.02.03 \"Interest Expense on Shareholder Loans\"" },
  { code: "PLF.11.01.01", label: "Change in Fair Value of Biological Assets (net)", kind: "own_account", storedCode: "PLF.11.01.01" },
  { code: "PLF.05.11.R", label: "Bad Debt Expense - G&A", kind: "own_account", storedCode: "PLF.05.11.R", duplicateOfCurrentCodes: ["PLF.05.11"] },
  { code: "PLF.05.17.R", label: "Foreign Exchange Gain/Loss - G&A", kind: "own_account", storedCode: "PLF.05.17.R", duplicateOfCurrentCodes: ["PLF.05.14"] },
  { code: "PLF.05.18.R", label: "Commission Fees - G&A", kind: "own_account", storedCode: "PLF.05.18.R", duplicateOfCurrentCodes: ["PLF.05.15"] },
  { code: "PLF.12.01.01", label: "Unused Vacations Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.01.FY2025.2", mintedBecause: "the current chart names PLF.12.01.01 \"Unused Vacations Provision - G&A\"" },
  { code: "PLF.12.01.02", label: "Annual Bonus Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.02.FY2025.2", mintedBecause: "the current chart names PLF.12.01.02 \"Annual Bonus Provision - G&A\"" },
  { code: "PLF.12.01.03", label: "Contingent Tax Liabilities Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.03.FY2025.2", mintedBecause: "the current chart names PLF.12.01.03 \"Tax Liabilities Provision - G&A\"" },
  { code: "PLF.12.01.04", label: "Receivable Allowance Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.04.FY2025.2", mintedBecause: "the current chart names PLF.12.01.04 \"Receivable Allowance Provision - G&A\"" },
  { code: "PLF.12.01.05", label: "Prepayment Allowance Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.05.FY2025.2", mintedBecause: "the current chart names PLF.12.01.05 \"Prepayment Allowance Provision - G&A\"" },
  { code: "PLF.12.01.06", label: "Inventory Impairment Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.06.FY2025.2", mintedBecause: "the current chart names PLF.12.01.06 \"Inventory Impairment Provision - G&A\"" },
  { code: "PLF.12.01.07", label: "Legal Dispute Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.07.FY2025.2", mintedBecause: "the current chart names PLF.12.01.07 \"Finished Goods Impairment Provision - G&A\"" },
  { code: "PLF.12.01.08", label: "Expense Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.08.FY2025.2", mintedBecause: "the current chart names PLF.12.01.08 \"Legal Dispute Provision - G&A\"" },
  { code: "PLF.12.01.99", label: "Other Provision - CoGS", kind: "own_account", storedCode: "PLF.12.01.99.FY2025.2", mintedBecause: "the current chart names PLF.12.01.99 \"Other Provision - G&A\"" },
  { code: "PLF.12.02.01", label: "Unused Vacations Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.01.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.01 as \"Unused Vacations Accrual - S&M\"" },
  { code: "PLF.12.02.02", label: "Annual Bonus Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.02.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.02 as \"Annual Bonus Accrual - S&M\"" },
  { code: "PLF.12.02.03", label: "Contingent Tax Liabilities Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.03.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.03 as \"Contingent Tax Liabilities Accrual - S&M\"" },
  { code: "PLF.12.02.04", label: "Receivable Allowance Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.04.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.04 as \"Receivable Allowance Accrual - S&M\"" },
  { code: "PLF.12.02.05", label: "Prepayment Allowance Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.05.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.05 as \"Prepayment Allowance Accrual - S&M\"" },
  { code: "PLF.12.02.06", label: "Inventory Impairment Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.06.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.06 as \"Inventory Impairment Accrual - S&M\"" },
  { code: "PLF.12.02.07", label: "Legal Dispute Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.07.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.07 as \"Legal Dispute Accrual - S&M\"" },
  { code: "PLF.12.02.08", label: "Expense Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.08.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.08 as \"Expense Accruals - S&M\"" },
  { code: "PLF.12.02.99", label: "Other Provision - S&M", kind: "own_account", storedCode: "PLF.12.02.99.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.02.99 as \"Other Accruals - S&M\"" },
  { code: "PLF.12.03.03", label: "Contingent Tax Liabilities Provision - G&A", kind: "own_account", storedCode: "PLF.12.03.03.FY2025", mintedBecause: "another 2025 row already posts to PLF.12.03.03 as \"Contingent Tax Liabilities Accrual - G&A\"" },
  { code: "PLF.08.02", label: "Expenses of prior periods", kind: "own_account", storedCode: "PLF.08.02", duplicateOfCurrentCodes: ["PLF.PY"] },
  { code: "PLF.08.03", label: "EDEN", kind: "own_account", storedCode: "PLF.08.03", duplicateOfCurrentCodes: ["PLF.EDEN"] },
]

/**
 * Indexed for the importer's per-row lookup. The key is the (code, LABEL)
 * pair — `PLF.07.02.04` carries three different subsidies on the 2025 sheet.
 */
export const PLF_2025_CHART_BY_KEY: ReadonlyMap<string, LegacyChartEntry> =
  new Map(PLF_2025_CHART_ENTRIES.map((e) => [legacyEntryKey(e.code, e.label), e]))
