"use client";

// Phase 9.8 — Trade alert inbox: open alerts with acknowledge, recent
// auto-resolved history. Alerts are generated by the pacing evaluator
// (POST /api/trade/alerts/recompute) once 9.3/9.5 feed snapshot data.

import { useCallback, useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { BellRing, Check } from "lucide-react";
import { SkeletonBlock } from "./SkeletonBlock";

interface TradeAlert {
  id: string;
  severity: "info" | "warn" | "critical";
  title: string;
  message: string;
  messageKey: string | null;
  messageParams: Record<string, string> | null;
  triggeredAt: string;
  acknowledgedAt: string | null;
  resolvedAt: string | null;
}

const SEVERITY_DOT: Record<string, string> = {
  critical: "bg-rose-500",
  warn: "bg-amber-500",
  info: "bg-sky-500",
};

export function TradeAlertInbox() {
  const t = useTranslations("trade.alerts");
  const tr = useTranslations("trade.alertRules");

  // R5 — render localized when the alert carries a messageKey; the stored
  // EN strings stay the fallback (pre-R5 rows, unknown keys).
  const localized = (a: TradeAlert): { title: string; message: string } => {
    if (!a.messageKey) return { title: a.title, message: a.message };
    try {
      const params = a.messageParams ?? {};
      return {
        title: tr(`${a.messageKey}.title`, params),
        message: tr(`${a.messageKey}.message`, params),
      };
    } catch {
      return { title: a.title, message: a.message };
    }
  };
  const [open, setOpen] = useState<TradeAlert[] | null>(null);
  const [resolvedCount, setResolvedCount] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    try {
      const res = await fetch("/api/trade/alerts");
      if (!res.ok) throw new Error(String(res.status));
      const data = await res.json();
      setOpen(data.open as TradeAlert[]);
      setResolvedCount((data.resolved as TradeAlert[]).length);
    } catch {
      setError(t("loadFailed"));
    }
  }, [t]);

  useEffect(() => {
    void load();
  }, [load]);

  const ack = useCallback(
    async (id: string) => {
      setBusy(true);
      try {
        await fetch(`/api/trade/alerts/${id}/ack`, { method: "POST" });
        void load();
      } finally {
        setBusy(false);
      }
    },
    [load],
  );

  return (
    <section className="rounded-lg border p-4">
      <h2 className="mb-3 flex items-center gap-2 text-sm font-semibold">
        <BellRing className="h-4 w-4" /> {t("title")}
        {open && open.length > 0 && (
          <span className="rounded-full bg-rose-100 px-2 py-0.5 text-[10px] font-semibold text-rose-800">
            {open.length}
          </span>
        )}
      </h2>
      {error && <p className="text-sm text-destructive">{error}</p>}
      {open === null ? (
        <SkeletonBlock lines={2} />
      ) : open.length === 0 ? (
        <p className="text-sm text-muted-foreground">{t("empty")}</p>
      ) : (
        <ul className="space-y-2">
          {open.map((a) => (
            <li key={a.id} className="flex items-start gap-2 rounded-md border p-2">
              <span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${SEVERITY_DOT[a.severity]}`} />
              <div className="min-w-0 flex-1">
                <div className="text-sm font-medium">{localized(a).title}</div>
                <p className="text-xs text-muted-foreground">{localized(a).message}</p>
                <div className="mt-0.5 text-[10px] text-muted-foreground">
                  {new Date(a.triggeredAt).toLocaleString()}
                  {a.acknowledgedAt && <span className="ml-2">✓ {t("acked")}</span>}
                </div>
              </div>
              {!a.acknowledgedAt && (
                <button
                  type="button"
                  disabled={busy}
                  onClick={() => void ack(a.id)}
                  title={t("ack")}
                  className="flex items-center gap-1 rounded-md border px-2 py-1 text-xs disabled:opacity-50"
                >
                  <Check className="h-3 w-3" /> {t("ack")}
                </button>
              )}
            </li>
          ))}
        </ul>
      )}
      {resolvedCount > 0 && (
        <p className="mt-2 text-xs text-muted-foreground">
          {t("resolvedRecently", { count: resolvedCount })}
        </p>
      )}
    </section>
  );
}
