/**
 * Emit the scenario catalog as SQL, so production can be seeded without
 * shipping a tsx runtime into the production image.
 *
 * `scripts/seed-crisis-scenarios.ts` is the local/dev runner and talks Prisma.
 * On prod there is no `tsx`, no `node_modules` and no repo checkout — only the
 * built Next standalone bundle and a psql inside the db container. Rather than
 * hand-writing the 14 rows a second time (two sources of truth, guaranteed to
 * drift), this prints them FROM `CRISIS_CATALOG`, and `deploy/seed-prod-scenarios.sh`
 * pipes the output straight into psql.
 *
 * The generated SQL is an UPSERT that preserves `overrides->'adjustments'`,
 * matching the Prisma runner's behaviour exactly: the catalog owns `shock`, a
 * human owns anything else on the row.
 *
 *   npx tsx scripts/emit-scenario-seed-sql.ts > /tmp/seed.sql
 */
import { CRISIS_CATALOG } from '../src/lib/risk/crisis-catalog'

/** Single-quote escaping for SQL literals — the values are ours, but a name
 *  with an apostrophe (there are Azerbaijani ones) would otherwise break out. */
function lit(v: string | null | undefined): string {
  if (v === null || v === undefined) return 'NULL'
  return `'${v.replace(/'/g, "''")}'`
}

const rows = CRISIS_CATALOG.map((s) => {
  const shock = JSON.stringify({ shock: s.shock })
  return `  (${lit(s.code)}, ${lit(s.nameEn)}, ${lit(s.nameRu)}, ${lit(s.nameAz)}, ${lit(s.description)}, ${lit(shock)}::jsonb)`
}).join(',\n')

process.stdout.write(`-- GENERATED by scripts/emit-scenario-seed-sql.ts — do not edit by hand.
-- Source of truth: src/lib/risk/crisis-catalog.ts (${CRISIS_CATALOG.length} scenarios)
BEGIN;

-- Refuse to guess. This deployment is single-tenant; if that ever stops being
-- true the seed must be told which org, not pick one silently.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM "Organization";
  IF n <> 1 THEN
    RAISE EXCEPTION 'Expected exactly 1 organization, found % — refusing to guess which one owns the catalog.', n;
  END IF;
END $$;

CREATE TEMP TABLE _cat (code text, name_en text, name_ru text, name_az text, descr text, overrides jsonb) ON COMMIT DROP;
INSERT INTO _cat (code, name_en, name_ru, name_az, descr, overrides) VALUES
${rows};

-- Update existing rows, keeping any human-authored adjustments on them.
UPDATE scenarios s
SET "nameEn" = c.name_en,
    "nameRu" = c.name_ru,
    "nameAz" = c.name_az,
    description = c.descr,
    overrides = c.overrides || CASE WHEN s.overrides ? 'adjustments'
                                    THEN jsonb_build_object('adjustments', s.overrides->'adjustments')
                                    ELSE '{}'::jsonb END,
    "isActive" = true,
    "updatedAt" = now()
FROM _cat c
WHERE s.code = c.code;

-- Insert the ones that do not exist yet.
INSERT INTO scenarios (id, "organizationId", code, "nameEn", "nameRu", "nameAz", description, overrides, "isActive", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, (SELECT id FROM "Organization" LIMIT 1),
       c.code, c.name_en, c.name_ru, c.name_az, c.descr, c.overrides, true, now(), now()
FROM _cat c
WHERE NOT EXISTS (SELECT 1 FROM scenarios s WHERE s.code = c.code);

COMMIT;

\\echo '=== scenarios now on this database ==='
SELECT code, "isActive", overrides->'shock' AS shock FROM scenarios ORDER BY code;
`)
